# Generated by Django 3.2.5 on 2021-10-02 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_name', models.CharField(max_length=30)),
                ('prof_img', models.ImageField(upload_to='pics')),
                ('prof_desc', models.TextField()),
                ('income', models.BigIntegerField()),
                ('expend', models.BigIntegerField()),
                ('risk', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks', models.IntegerField(default=100)),
                ('mutual_funds', models.IntegerField(default=100)),
                ('fds', models.IntegerField(default=100)),
                ('gold', models.IntegerField(default=100)),
                ('loans', models.IntegerField(default=100)),
                ('balance', models.IntegerField(default=100)),
                ('prtf_name', models.CharField(max_length=30)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profession.profession')),
            ],
        ),
    ]
